name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *' # Runs Every 24 Hours
permissions:
  contents: write # To write the generated contents to the readme
  
jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.1.1"
        with:
          USERNAME: 'Kunal Verma' # Hashnode Username
          COUNT: 6 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://kunalverma2468.hashnode.dev"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
